name: Guardar Datos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Guardar datos
      run: |
        echo "Datos del jugador" > datos.txt
        git add datos.txt
        git commit -m "Guardar datos del jugador"
        git push
